config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  unauthenticated :user do
    root 'home#index'
  end

  authenticated :user do
    root 'word_cards#index'
    resources :word_cards do
      collection do
        get :study
        get :study_word
      end
      resources :word_card_results, only: [:create]
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  provider               :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  uid                    :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
  devise :omniauthable, omniauth_providers: %i[google_oauth2]

  has_many :word_cards

  class << self
    def from_omniauth(auth)
      user = User.find_by(uid: auth.uid, provider: auth.provider)
      if user.nil?
        user = User.create!(
            uid: auth.uid,
            provider: auth.provider,
            email: auth.info.email,
            password: Devise.friendly_token[0, 20]
        )
      end
      user
    end
  end
end

app/models/word_card.rb
# == Schema Information
#
# Table name: word_cards
#
#  id          :bigint           not null, primary key
#  deleted_at  :datetime
#  description :text             not null
#  word        :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :integer          not null
#
# Indexes
#
#  index_word_cards_on_user_id  (user_id)
#

class WordCard < ApplicationRecord
  belongs_to :user
  default_scope -> { where(deleted_at: nil)}
  has_many :word_card_results
  has_one :word_card_result_summary
end

app/models/word_card_result.rb
# == Schema Information
#
# Table name: word_card_results
#
#  id           :bigint           not null, primary key
#  remember     :boolean          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  word_card_id :integer          not null
#
# Indexes
#
#  index_word_card_results_on_word_card_id_and_created_at  (word_card_id,created_at)
#

class WordCardResult < ApplicationRecord
  belongs_to :word_card
  after_commit -> do
    begin
      ActiveRecord::Base.transaction do
        user = word_card.user
        conn = ActiveRecord::Base.connection
        sql = <<-sql
    delete from word_card_result_summaries 
    where word_card_id in (select id from word_cards where user_id = ? and deleted_at is null)
        sql
        sql = ActiveRecord::Base.send(
            :sanitize_sql_array,
            [sql, user.id]
        )
        conn.execute(sql)

        sql = <<-sql
insert into word_card_result_summaries (word_card_id, result_count, remember_count, created_at, updated_at)
select 
  word_card_id,
  count(*) result_count,
  sum(case when remember then 1 else 0 end) remember_count,
  current_timestamp,
  current_timestamp
from (
  select *
  from word_card_results
  where word_card_id in (select id from word_cards where user_id = ? and deleted_at is null)
  order by created_at desc
  limit ?) sliced
group by word_card_id;
        sql
        sql = ActiveRecord::Base.send(
            :sanitize_sql_array,
            [sql, user.id, user.word_cards.count * 2]
        )
        conn.execute(sql)
      end
    end
 end
end

app/models/word_card_result_summary.rb
# == Schema Information
#
# Table name: word_card_result_summaries
#
#  id             :bigint           not null, primary key
#  remember_count :integer          not null
#  result_count   :integer          not null
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  word_card_id   :integer          not null
#
# Indexes
#
#  index_word_card_result_summaries_on_word_card_id  (word_card_id) UNIQUE
#

class WordCardResultSummary < ApplicationRecord
  belongs_to :word_card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to word_cards_path if current_user.present?
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    @user = User.from_omniauth(request.env['omniauth.auth'])

    if @user.persisted?
      flash[:notice] = I18n.t 'devise.omniauth_callbacks.success', kind: 'Google'
      sign_in_and_redirect @user, event: :authentication
    else
      session['devise.google_data'] = request.env['omniauth.auth'].except(:extra) # Removing extra as it can overflow some session stores
      redirect_to new_user_registration_url, alert: @user.errors.full_messages.join("\n")
    end
  end
end

app/controllers/word_card_results_controller.rb
class WordCardResultsController < ApplicationController
  def create
    @word_card = WordCard.find_by!(id: params[:word_card_id])
    @word_card.word_card_results.create(remember: params[:remember])
    head :ok
  end
end

app/controllers/word_cards_controller.rb
class WordCardsController < ApplicationController
  def index
    @word_cards = current_user.word_cards
  end

  def show
    redirect_to word_cards_path
  end

  def new
    @word_card = current_user.word_cards.build
  end

  def create
    @word_card = current_user.word_cards.build(word_card_params)
    if @word_card.save
      redirect_to @word_card
    else
      render :new
    end
  end

  def edit
    @word_card = current_user.word_cards.find_by(id: params[:id])
  end

  def update
    @word_card = current_user.word_cards.find_by(id: params[:id])
    if @word_card.update(word_card_params)
      redirect_to @word_card
    else
      render :edit
    end
  end

  def destroy
    @word_card = current_user.word_cards.find_by(id: params[:id])
    @word_card.update!(deleted_at: Time.zone.now)
    redirect_to word_cards_path
  end

  def study
    gon.word_cards = current_user.word_cards
  end

  def study_word
    r = SimpleRandom.new
    r.set_seed
    @word_card = current_user.word_cards
                     .includes(:word_card_result_summary)
                     .max_by do |word_card|
      summary = word_card.word_card_result_summary
      summary ||= word_card.build_word_card_result_summary(
          {
              remember_count: 0,
              result_count: 0,
          }
      )
      r.beta(summary.result_count - summary.remember_count + 1, summary.remember_count + 1)
    end
    render json: {word_card: @word_card}
  end

  private

  def word_card_params
    params.require(:word_card).permit(:word, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<%= link_to "Sign in with Google", user_google_oauth2_omniauth_authorize_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StudyApp</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    <%= Gon::Base.render_data %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container pt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/word_cards/edit.html.erb
<h2>単語作成</h2>
<%= form_for @word_card do |f| %>
  <div class="form-group">
    <%= f.label :word %>
    <%= f.text_field :word, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit '更新', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/word_cards/index.html.erb
<h2>単語一覧</h2>
<%= link_to '作成', new_word_card_path, class: 'btn btn-primary' %>
<%= link_to '勉強する', study_word_cards_path, class: 'btn btn-primary' %>
<table class="table">
  <thead>
  <tr>
    <td>word</td>
    <td>description</td>
    <td></td>
  </tr>
  </thead>

  <tbody>
  <% @word_cards.each do |word_card| %>
  <tr>
    <td><%= word_card.word %></td>
    <td style="white-space: pre-wrap;"><%= word_card.description %></td>
    <td>
      <div class="btn-group">
        <%= link_to '編集', edit_word_card_path(word_card), class: 'btn btn-sm btn-warning' %>
        <%= link_to '削除', word_card_path(word_card), class: 'btn btn-sm btn-danger', method: :delete, data: { confirm: '削除しますか？' } %>
      </div>
    </td>
  </tr>
  <% end %>
  </tbody>
</table>

app/views/word_cards/new.html.erb
<h2>単語作成</h2>
<%= form_for @word_card do |f| %>
  <div class="form-group">
    <%= f.label :word %>
    <%= f.text_field :word, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit '作成', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/word_cards/study.html.erb
<div id="word_cards-study">
  <h2 id="word"></h2>
  <pre id="description"></pre>
  <div class="row">
    <div class="btn-group">
      <button type="button" class="btn btn-success" id="button-remember">覚えていた</button>
      <button type="button" class="btn btn-warning" id="button-forget">忘れてた</button>
    </div>
  </div>
  <div class="row mt-3">
    <div class="btn-group">
      <button type="button" class="btn btn-primary" id="button-answer">答えを見る</button>
      <button type="button" class="btn btn-info" id="button-next">次へ</button>
    </div>
  </div>
</div>